### ISSUE TITLE
No subgroup and gtf file is created after running the software

### ISSUE THREAD

**Issue by ruixuan-zhang** [shenkers/isoscm#23]
Hi everyone, I met some problems when using this software.
I basically follow the guide and my argument are a BAM, a base name, and reverse_forward.

Then, I got this, I think there is nothing wrong with it
```
2020-10-21T09:26:11,643 [main] INFO  executable.IsoSCM - IsoSCM 2.0.12
2020-10-21T09:26:17,463 [main] INFO  executable.IsoSCM - Command: java -jar  IsoSCM-2.0.12.jar assemble -bam /aptmp/ruixuan/medusavirus_paper/mapping_result/merged_genome/MVPI16/MVPI16_sort.bam -base medusa -s reverse_forward
2020-10-21T09:26:17,484 [main] INFO  executable.IsoSCM - Starting assemble ...
2020-10-21T09:26:17,632 [main] INFO  executable.IsoSCM - tabulating splice junctions...
Exception in thread "main" java.lang.NullPointerException
	at processing.FindSpliceJunctions.tabulateSpliceJunctions(FindSpliceJunctions.java:148)
	at executable.IsoSCM.main(IsoSCM.java:240)
```
But as a result, I only have 
```
`
|--- log file
|--- isoscm folder
       |----a XML file 
       |----tmp folder (containing an empty bed file with my base name)
```

So I'm not sure I got the right output from this software and what should I do to correct it?
Thank you

**Comment by shenkers** [comment]
Hi Richard,

How did you align the reads? IsoSCM expects the reads to have a flag that
indicates the strand inferred from the splice junction motifs. I know this
flag was added by tophat, but I'm not sure about other tools.

**Comment by francicco** [comment]
Hi I'm having the same problem.
I aligned the reads with STAR
Cheers
F

**Comment by shenkers** [comment]
Hi @francicco, IsoSCM depends on the aligner setting an XS flag in order to infer the read strandedness. I did a search, and it looks like the author of STAR has actually added a flag for this `-outSAMattributes XS` (from this GH issue https://github.com/alexdobin/STAR/issues/567 ). Does running STAR with this flag help solve this problem?

**Comment by shenkers** [comment]
@francicco It looks like iRNA-COSI has made a nextflow workflow for running IsoSCM. They're using STAR for the alignments, and they are adding the XS flag https://github.com/iRNA-COSI/APAeval/blob/main/execution_workflows/IsoSCM/modules/star_alignment.nf
