### ISSUE TITLE
ERROR: Inappropriate call if not paired read

### ISSUE THREAD

**Issue by antonkulaga** [shenkers/isoscm#3]
When I try to apply isoscm to my bam I get

```
Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read
    at net.sf.samtools.SAMRecord.requireReadPaired(SAMRecord.java:676)
    at net.sf.samtools.SAMRecord.getFirstOfPairFlag(SAMRecord.java:734)
    at tools.BAMTools.strand(BAMTools.java:1022)
    at processing.FindSpliceJunctions.updateJunctionCounts2(FindSpliceJunctions.java:758)
    at processing.FindSpliceJunctions.countJunctionSupportingReads(FindSpliceJunctions.java:883)
```

**Comment by shenkers** [comment]
Hi Anton,

Without knowing more about how you are running IsoSCM and what parameters you are using and how you generated your bam file I have two guesses:
1. You have used the "reverse_forward" flag (parameter -s) for data that is unpaired.  
2. The BAM file you are analyzing is not properly formatted. If you pass IsoSCM the reverse_forward flag, it expects SAM records to have a flag set specifying whether it is first or second read of the pair. The SAM spec describes the flag field in section 1.4.2:

http://samtools.github.io/hts-specs/SAMv1.pdf

If a read is paired either bit 0x40 or 0x80 of the flag should be set, otherwise this error will be thrown.

In either of these cases specifying "unstranded" as the strandedness (parameter -s) of the BAM file can be used to avoid this exception.

**Comment by antonkulaga** [comment]
Thank you! First option worked well.
