### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by antonkulaga** [shenkers/isoscm#5]
When I apply isoscm to my bams I get null pointer exception: 

```
[root@ftp 3_tophat]# java -Xmx2048m -jar /opt/isoscm/iso.jar assemble -bam 3.bam -s unstranded -base flies -dir /home/uploader/flies/assembly5/utrs
2015-04-15T17:17:36,680 [main] INFO  executable.IsoSCM - Starting assemble ...
2015-04-15T17:17:36,990 [main] INFO  executable.IsoSCM - tabulating splice junctions...
2015-04-15T17:18:00,762 [main] INFO  executable.IsoSCM - counting junction supporting reads...
2015-04-15T17:28:06,321 [main] INFO  executable.IsoSCM - identifying covered segments...
2015-04-15T17:31:19,465 [main] INFO  executable.IsoSCM - merging coverage gaps less than 100 bp...
2015-04-15T17:31:20,194 [main] INFO  executable.IsoSCM - filtering splice junctions...
Exception in thread "main" java.lang.NullPointerException
    at processing.FindSpliceJunctions.filterCountedJunctions(FindSpliceJunctions.java:1036)
    at executable.IsoSCM.main(IsoSCM.java:300)
```

**Comment by shenkers** [comment]
Hi Anton,
What version of IsoSCM are you using? This looks similar to an error that was previously reported, but should be patched in the latest release.

**Comment by antonkulaga** [comment]
I build IsoSCM from source and I am still having such error in my bam

**Comment by shenkers** [comment]
Hmm, thanks. I don't think I'm going to be able to figure this out without some more information. Is it possible for you to share the file that is causing the issue? If it is possible to reduce the bam file to a smaller set of reads that reproduces the problem that would be helpful for debugging.

Also, these files would be useful for me to look at:

/home/uploader/flies/assembly5/utrs/tmp/flies.sj.bed
/home/uploader/flies/assembly5/utrs/tmp/flies.sj.counted.gtf

**Comment by antonkulaga** [comment]
here is the bam that caused problem: https://drive.google.com/file/d/0B53nZMQJitqOUmlQMUtSenczM2M/view?usp=sharing
here are files that were generated by isoscm https://drive.google.com/file/d/0B53nZMQJitqOV183Z0FkbUx3eVU/view?usp=sharing

**Comment by shenkers** [comment]
Thanks, that was useful, the intron that's causing the problem has a 5' boundary at 3R:31390359. It looks like it's getting mixed up when there's a deletion right before the intron in the cigar string (ie when the CIGAR string matches "[0-9]M[0-9]+D[0-9]+N[0-9]+M". I'll let you know when I have a fix!

**Comment by shenkers** [comment]
I've uploaded a [version 2.0.7](https://github.com/shenkers/isoscm/releases/tag/2.0.7) that should fix this error. I ran it on the file you shared and it completes without error now. Thanks for reporting this, and let me know if you run into any other issues.

Sol
